// Code generated by rice embed-go; DO NOT EDIT.
package main

import (
	"time"

	"github.com/GeertJohan/go.rice/embedded"
)

func init() {

	// define files
	file2 := &embedded.EmbeddedFile{
		Filename:    "app.js",
		FileModTime: time.Unix(1621389644, 0),

		Content: string("console.log(\"Bobo\");\n"),
	}
	file3 := &embedded.EmbeddedFile{
		Filename:    "index.html",
		FileModTime: time.Unix(1621389644, 0),

		Content: string("<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n       <meta charset=\"UTF-8\">\n       <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n       <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n       <title>Document</title>\n\n       <link rel=\"stylesheet\" href=\"styles.css\" />\n\n</head>\n\n<body>\n\n       <h1>Esto es una pagina web</h1>\n\n\n       <script src=\"app.js\"></script>\n</body>\n\n</html>"),
	}
	file4 := &embedded.EmbeddedFile{
		Filename:    "page.html",
		FileModTime: time.Unix(1621389644, 0),

		Content: string("<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n       <meta charset=\"UTF-8\">\n       <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n       <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n       <title>Document</title>\n\n       <link rel=\"stylesheet\" href=\"styles.css\" />\n\n</head>\n\n<body>\n\n       <h1>Esto es una pagina web</h1>\n\n\n       <script src=\"app.js\"></script>\n</body>\n\n</html>"),
	}
	file5 := &embedded.EmbeddedFile{
		Filename:    "styles.css",
		FileModTime: time.Unix(1621389644, 0),

		Content: string("body {\n       background-color: rgb(24, 24, 24);\n}\n\np,\nh1,\nh2,\nh3,\nh4,\nh5,\nh6 {\n       color: rgb(231, 231, 231);\n}\n"),
	}

	// define dirs
	dir1 := &embedded.EmbeddedDir{
		Filename:   "",
		DirModTime: time.Unix(1621389644, 0),
		ChildFiles: []*embedded.EmbeddedFile{
			file2, // "app.js"
			file3, // "index.html"
			file4, // "page.html"
			file5, // "styles.css"

		},
	}

	// link ChildDirs
	dir1.ChildDirs = []*embedded.EmbeddedDir{}

	// register embeddedBox
	embedded.RegisterEmbeddedBox(`web`, &embedded.EmbeddedBox{
		Name: `web`,
		Time: time.Unix(1621389644, 0),
		Dirs: map[string]*embedded.EmbeddedDir{
			"": dir1,
		},
		Files: map[string]*embedded.EmbeddedFile{
			"app.js":     file2,
			"index.html": file3,
			"page.html":  file4,
			"styles.css": file5,
		},
	})
}
